In [19]:
def solution(diffs, times, limit):
    if limit==sum(diffs):
        answer = max(diffs)
        return answer
    lvl_low=0
    lvl_high=max(diffs)
    at_low = 0
    at_high = 1
    answer=max(diffs)
    while True:
        print(lvl_low, lvl_high, answer)
        temp_lvl = int((lvl_low+lvl_high)/2)
        # calculate temp_t using temp_lvl
        temp_t = 0
        for i in range(len(diffs)):
            if diffs[i] <= temp_lvl:
                temp_t+=times[i]
            else:
                temp_t+=(diffs[i]-temp_lvl)*(times[i-1]+times[i])+times[i]
        if temp_t == limit:
            answer = temp_lvl
            break
        elif temp_t > limit:
            lvl_low = temp_lvl
            t_low = 0
        elif temp_t < limit:
            lvl_high = temp_lvl
            t_high = temp_t
        if lvl_high-lvl_low==1:
            answer = lvl_high
            break
        if lvl_high <= lvl_low:
            answer = temp_lvl
            break
    return answer

In [20]:
diffs = [1, 5, 3]
times = [2, 4, 7]
limit=30
solution(diffs, times, limit)

0 5 5
2 5 5

3

In [75]:
from collections import Counter

def solution(points, routes):
    # find each route 
    newroutes=[]
    max_ticks= 0
    for route in routes:
        p1 = points[route[0]-1]
        newroute = [(p1[0], p1[1])]
        for i in range(len(route)-1):
            p1 = points[route[i]-1]
            p2 = points[route[i+1]-1]
            print(p1, p2)
            p_t = p1
            while True:
                print(p_t)
                if p_t[0]<p2[0]:
                    p_t=(p_t[0]+1,p_t[1])
                    newroute.append(p_t)
                elif p2[0]<p_t[0]:
                    p_t=(p_t[0]-1,p_t[1])
                    newroute.append(p_t)
                elif p_t[1]<p2[1]:
                    p_t=(p_t[0],p_t[1]+1)
                    newroute.append(p_t)
                elif p2[1]<p_t[1]:
                    p_t=(p_t[0],p_t[1]-1)
                    newroute.append(p_t)
                else:
                    break
        newroutes.append(newroute)
        if max_ticks<len(newroute):
            max_ticks=len(newroute)
    print(newroutes)
    answer=0
    for i in range(max_ticks):
        # first check if i is within range
        check = []
        for j in range(len(routes)):
            if i < len(newroutes[j]):
                check.append(newroutes[j][i])
        # print(check)
        # print(Counter(check))
        counter = Counter(check)
        for key in counter:
            if counter[key]>=2:
                answer+=1
    return answer

In [77]:
# points=[[2, 2], [2, 3], [2, 7], [6, 6], [5, 2]]
# routes=[[2, 3, 4, 5], [1, 3, 4, 5]]
points = [[3, 2], [6, 4], [4, 7], [1, 4]]
routes = [[4, 2], [1, 3], [2, 4]]
solution(points, routes)

[1, 4] [6, 4]
[1, 4]
(2, 4)
(3, 4)
(4, 4)
(5, 4)
(6, 4)
[3, 2] [4, 7]
[3, 2]
(4, 2)
(4, 3)
(4, 4)
(4, 5)
(4, 6)
(4, 7)
[6, 4] [1, 4]
[6, 4]
(5, 4)
(4, 4)
(3, 4)
(2, 4)
(1, 4)
[[(1, 4), (2, 4), (3, 4), (4, 4), (5, 4), (6, 4)], [(3, 2), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7)], [(6, 4), (5, 4), (4, 4), (3, 4), (2, 4), (1, 4)]]

1

In [168]:
from collections import Counter
def solution(edges):
    # go through to find node with only outgoing shit
    ins = []
    outs = []
    # counts = []
    dict_map = {}
    dict_map_out = {}
    for node_in, node_out in edges:
        if node_in in dict_map.keys():
            dict_map[node_in].append(node_out)
        else:
            dict_map[node_in]=[node_out]
        if node_out in dict_map_out.keys():
            dict_map_out[node_out].append(node_in)
        else:
            dict_map_out[node_out]=[node_in]
        ins.append(node_in)
        outs.append(node_out)
        # counts.append(node_in)
    # counts = Counter(counts)
    ins = set(ins)
    outs = set(outs)
    newnode = list(ins-outs)
    for node in newnode:
        if len(dict_map[node])>1:
            newnode = node
            break
    print(newnode)
    # print(dict_map)
    # print(dict_map_out)
    stick=0
    donut=0
    eight=0
    for node in dict_map[newnode]:
        #continue chain
        # if there is an end, this is stick
        # if comes to same one, this is donut
        # if there are two choices, this is 8
        start = node
        while True:
            if node not in dict_map:
                stick+=1
                break
            test = dict_map[node]
            if len(test)>1:
                eight+=1
                break
            if test[0]==start:
                donut+=1
                break
            node=test[0]
    answer = [newnode, donut, stick, eight]
    return answer

In [169]:
# edges=[[2, 3], [4, 3], [1, 1], [2, 1]]
edges=[[4, 11], [1, 12], [8, 3], [12, 7], [4, 2], [7, 11], [4, 8], [9, 6], [10, 11], [6, 10], [3, 5], [11, 1], [5, 3], [11, 9], [3, 8]]
solution(edges)

4

[4, 0, 1, 2]

In [137]:
a=[1,2,3,4]
b=a.copy()
b.remove(3)

In [140]:
b

[1, 2, 4]

In [146]:
b.remove(1)
b.remove(2)

In [147]:
b

[4]

In [111]:
# https://school.programmers.co.kr/learn/courses/30/lessons/340210
from collections import Counter
def solution(expressions):
    exps = []
    for exp in expressions:
        exps.append(exp.split())
    valids = []
    largerthan=0
    nonX=0
    for exp in exps:
        num1 = exp[0]
        sign = exp[1]
        num2 = exp[2]
        ans = exp[4]
        # if ans=='X':
        #     continue
        allnums = num1+num2+ans
        if ans=='X':
            allnums = num1+num2
            nonX+=1
        if int(largerthan) < int(max(allnums)):
            largerthan = max(allnums)
    
    for exp in exps:
        num1 = exp[0]
        sign = exp[1]
        num2 = exp[2]
        ans = exp[4]
        if ans=='X':
            continue
        
        for i in range(int(largerthan)+1,10):
            # print(i)
            #calculate equation and find valid candidates
            num1_int=0
            num2_int=0
            ans_int=0
            for j in range(len(num1)):
                num1_int+=(i**(len(num1)-1-j))*int(num1[j])
            for j in range(len(num2)):
                num2_int+=(i**(len(num2)-1-j))*int(num2[j])
            for j in range(len(ans)):
                ans_int+=(i**(len(ans)-1-j))*int(ans[j])
            if sign=='-':
                eq=num1_int-num2_int-ans_int
            else:
                eq=num1_int+num2_int-ans_int
            if eq==0:
                valids.append(i)
            # print(num1_int, num2_int, ans_int, eq)
    print(valids)
    counters = Counter(valids)
    base = []
    for key in counters.keys():
        if counters[key]>=nonX:
            base.append(key)
    print(base)
    eqs = {}
    for b in base:
        eqs[b]=[]
        for exp in exps:
            num1 = exp[0]
            sign = exp[1]
            num2 = exp[2]
            ans = exp[4]
            num1_int=0
            num2_int=0
            if ans!='X':
                continue
            for j in range(len(num1)):
                num1_int+=(b**(len(num1)-1-j))*int(num1[j])
            for j in range(len(num2)):
                num2_int+=(b**(len(num2)-1-j))*int(num2[j])
            # print(num1_int, num2_int)
            if sign=='-':
                eq=num1_int-num2_int
            else:
                eq=num1_int+num2_int
            eqs[b].append(eq)
            
    print(eqs)
    answer = {}
    for b in base:
        answer[b]=[]
        for i in range(len(eqs[b])):
            quant = eqs[b][i]
            eq = eqs[b][i]
            print(quant, 'asdfasdf')
            answer[b].append('')
            while True:
                if quant==0:
                    break
                rem = eq%b
                quant = eq//b
                answer[b][i]=str(rem)+answer[b][i]
                eq=quant
        # print(answer[b])
        answer[b]=set(answer[b])
    print(answer)
    answer_t = []
    for key in answer.keys():
        if answer[key]>1:
            answer_t.append('?')
        else:
            answer_t.append(answer[key])
    return answer

In [112]:
# expressions = ["14 + 3 = 17", "13 - 6 = X", "51 - 5 = 44"]
expressions = ["1 + 1 = 2", "1 + 3 = 4", "1 + 5 = X", "1 + 2 = X"]
# expressions = ["10 - 2 = X", "30 + 31 = 101", "3 + 3 = X", "33 + 33 = X"]
solution(expressions)

[6, 7, 8, 9, 6, 7, 8, 9]
[6, 7, 8, 9]
{6: [6, 3], 7: [6, 3], 8: [6, 3], 9: [6, 3]}
6 asdfasdf
3 asdfasdf
6 asdfasdf
3 asdfasdf
6 asdfasdf
3 asdfasdf
6 asdfasdf
3 asdfasdf
{6: {'3', '10'}, 7: {'6', '3'}, 8: {'6', '3'}, 9: {'6', '3'}}

TypeError: '>' not supported between instances of 'set' and 'int'

In [39]:
a=3**1

In [40]:
a

3

In [60]:
13//5

2

In [148]:
def solution(N):
    # Implement your solution here
    if N%2==0:
        a=list(range(1, int(N/2)+1))
        b=list(range(-1*int(N/2), 0))
        a.extend(b)
        ans=a
    else:
        a=list(range(0, int(N/2)+1))
        b=list(range(-1*int(N/2), 0))
        a.extend(b)
        ans=a
    return ans

In [154]:
N=10
answer = solution(N)
print(answer)
print(sum(answer), len(set(answer)))

[1, 2, 3, 4, 5, -5, -4, -3, -2, -1]
0 10

In [200]:
def solution(indices, K):
    # Implement your solution here
    dataset_len = len(indices) // K
    remaining = len(indices) % K
    test_lens = [dataset_len + 1 if i < remaining else dataset_len for i in range(K)]
    # print(test_lens)
    test_lens_accuml = []
    for i in range(len(test_lens)+1):
        test_lens_accuml.append(sum(test_lens[:i]))
    # print(test_lens_accuml)
    
    answer = []
    for i in range(K):
        if i<K-1:
            test = indices[test_lens_accuml[i]: test_lens_accuml[i+1]]
            trainfront = indices[0: test_lens_accuml[i]]
            trainback = indices[test_lens_accuml[i+1]:]
        else:
            test = indices[test_lens_accuml[i]:]
            trainfront = indices[0: test_lens_accuml[i]]
            trainback = []
        trainfront.extend(trainback)
        answer.append(trainfront)
        answer.append(test)
    return answer

In [202]:
# indices=[1, 2, 3]
# K=2
indices=[10, 0, 3, 5, 12]
K=3
answer = solution(indices, K)
print(answer)

[0, 2, 4, 5]
[[3, 5, 12], [10, 0], [10, 0, 12], [3, 5], [10, 0, 3, 5], [12]]

In [162]:
indices=[1, 2, 3]
indices[2:]

[3]

In [1]:
from sklearn.cluster import KMeans
import sklearn.preprocessing as preprocessing
import sklearn.metrics as metrics
import pandas as pd
import numpy as np

df_train = pd.read_csv("data/data_train.csv")
df_test = pd.read_csv("data/data_test.csv")

In [2]:
df_stats = pd.DataFrame(df_train, columns=['account_1', 'account_2', 'account_3', 'account_4', 'account_5', 'account_6', 'account_7', 'account_8', 'account_9', 'account_10', 'account_11', 'account_12'])
mean=df_stats.stack().mean()
std=df_stats.stack().std()

cluster = df_train['cluster']
sd_train=((df_train-mean)/std).round(3)
# sd_train['cluster']=cluster

cluster = df_test['cluster']
sd_test=((df_test-mean)/std).round(3)
# sd_test['cluster']=cluster

In [3]:
wcss=[]
sd_train = pd.DataFrame(sd_train, columns=['account_1', 'account_2', 'account_3', 'account_4', 'account_5', 'account_6', 'account_7', 'account_8', 'account_9', 'account_10', 'account_11', 'account_12'])
sd_test = pd.DataFrame(sd_test, columns=['account_1', 'account_2', 'account_3', 'account_4', 'account_5', 'account_6', 'account_7', 'account_8', 'account_9', 'account_10', 'account_11', 'account_12'])
for i in range(2,11):
    km = KMeans(n_clusters=i, init="k-means++",max_iter=50,n_init=10,random_state=0,tol=0.05)
    km.fit(sd_train)
    wcss.append(km.inertia_)
opt_cluster=0
for i in range(len(wcss)-1):
    if wcss[i]-wcss[i+1]<20:
        opt_cluster=i+2
        break
print(opt_cluster)
print(wcss)

6
[5394.722313688438, 3531.032517362712, 2056.329321828265, 1027.3596889129535, 99.05420147267802, 97.40959328667577, 96.09982899342536, 94.60557069585286, 93.19463361572555]

In [21]:
kmeans_4 = KMeans(n_clusters=4, init="k-means++",max_iter=50,n_init=10,random_state=0,tol=0.05)
kmeans_4.fit(sd_train)

kmeans_opt = KMeans(n_clusters=opt_cluster, init="k-means++",max_iter=50,n_init=10,random_state=0,tol=0.05)
kmeans_opt.fit(sd_train)

import sklearn.metrics
score = sklearn.metrics.silhouette_score(sd_train, kmeans_opt.labels_)

kmeans_opt.fit(sd_test)
labels_predicted = kmeans_opt.labels_

In [22]:
a = sklearn.metrics.cluster.completeness_score(kmeans_4.labels_, list(df_train['cluster']))
kmeans_4.fit(sd_test)
b = sklearn.metrics.cluster.completeness_score(kmeans_4.labels_, list(df_test['cluster']))

In [20]:

# df_test.shape

In [37]:
kmeans_4.labels_.shape

(950,)

In [40]:
len(list(df_test['cluster']))

50

In [9]:
kmeans_opt.fit(sd_train)
kmeans_opt.labels_
# kmeans_opt.predict(sd_test)
centers = kmeans_opt.cluster_centers_

In [10]:
len(centers)

6

In [11]:
import numpy as np
first = np.array(sd_test.iloc[0])
distances = []
for i in range(len(centers)):
    distances.append(np.linalg.norm(first-centers[i]))

In [12]:
distances

[5.123102371427395,
 0.3228054323857058,
 4.12274776082811,
 3.5225767441015856,
 4.3343504103357375,
 3.757818980795789]

In [21]:
ascending = np.argsort(distances)
max_opt = []
for i in range(len(ascending)):
    max_opt.append(ascending[-1-i])

In [22]:
max_opt

[0, 4, 2, 5, 3, 1]

In [37]:
from sklearn.cluster import KMeans
import sklearn.preprocessing as preprocessing
import sklearn.metrics as metrics
import pandas as pd
import numpy as np

df_train = pd.read_csv("data/data_train.csv")
df_test = pd.read_csv("data/data_test.csv")

df_stats = pd.DataFrame(df_train, columns=['account_1', 'account_2', 'account_3', 'account_4', 'account_5', 'account_6', 'account_7', 'account_8', 'account_9', 'account_10', 'account_11', 'account_12'])
mean=df_stats.stack().mean()
std=df_stats.stack().std()

cluster = df_train['cluster']
sd_train=((df_train-mean)/std).round(3)
# sd_train['cluster']=cluster

cluster = df_test['cluster']
sd_test=((df_test-mean)/std).round(3)
# sd_test['cluster']=cluster

wcss=[]
sd_train = pd.DataFrame(sd_train, columns=['account_1', 'account_2', 'account_3', 'account_4', 'account_5', 'account_6', 'account_7', 'account_8', 'account_9', 'account_10', 'account_11', 'account_12'])
sd_test = pd.DataFrame(sd_test, columns=['account_1', 'account_2', 'account_3', 'account_4', 'account_5', 'account_6', 'account_7', 'account_8', 'account_9', 'account_10', 'account_11', 'account_12'])

for i in range(2,11):
    km = KMeans(n_clusters=i, init="k-means++",max_iter=50,n_init=10,random_state=0,tol=0.05)
    km.fit(sd_train)
    wcss.append(km.inertia_)
opt_cluster=0
for i in range(len(wcss)-1):
    if wcss[i]-wcss[i+1]<20:
        opt_cluster=i+2
        break
# print(opt_cluster)
# print(wcss)

kmeans_4 = KMeans(n_clusters=4, init="k-means++",max_iter=50,n_init=10,random_state=0,tol=0.05)
kmeans_4.fit(sd_train)

kmeans_opt = KMeans(n_clusters=opt_cluster, init="k-means++",max_iter=50,n_init=10,random_state=0,tol=0.05)
kmeans_opt.fit(sd_train)

silhouette = metrics.silhouette_score(sd_train, kmeans_opt.labels_)


a = metrics.cluster.completeness_score(kmeans_4.labels_, list(df_train['cluster']))
kmeans_4.fit(sd_test)
b = metrics.cluster.completeness_score(kmeans_4.labels_, list(df_test['cluster']))
completeness=(a,b)

centers = kmeans_opt.cluster_centers_
first = np.array(sd_test.iloc[0])
distances = []
for i in range(len(centers)):
    distances.append(np.linalg.norm(first-centers[i]))
ascending = np.argsort(distances)
max_opt = []
for i in range(len(ascending)):
    max_opt.append(ascending[-1-i])


kmeans_opt.fit(sd_test)
labels_predicted = kmeans_opt.labels_

In [38]:
sd_train

,account_1,account_2,account_3,account_4,account_5,account_6,account_7,account_8,account_9,account_10,account_11,account_12
0,0.262,0.227,1.353,0.494,-0.657,-0.690,0.876,-0.792,1.059,0.174,-0.885,-0.896
1,-0.005,1.483,-0.962,-1.717,-1.839,0.271,1.033,1.895,2.199,0.714,-0.197,0.810
2,0.265,0.393,1.333,0.520,-0.702,-0.705,0.979,-0.919,1.091,0.201,-0.901,-1.009
3,-0.620,-0.600,0.227,-0.274,1.138,-1.253,-0.997,-0.443,0.709,-0.985,-0.197,-0.638
4,-0.075,0.734,0.431,-0.126,-0.565,-0.151,-0.116,1.803,2.052,-0.641,0.557,0.080
...,...,...,...,...,...,...,...,...,...,...,...,...
945,0.172,0.435,1.367,0.586,-0.725,-0.626,0.764,-0.713,0.912,0.143,-0.849,-1.006
946,0.126,1.463,-0.954,-1.555,-1.723,0.319,1.115,1.854,2.073,0.441,-0.307,0.668
947,-0.045,0.767,0.361,0.007,-0.678,-0.069,-0.177,1.831,1.980,-0.672,0.467,-0.055
948,-0.063,1.512,-1.055,-1.806,-1.859,0.241,1.159,1.726,2.110,0.457,-0.292,0.741
949,-0.113,1.735,-0.914,-1.777,-1.766,0.489,1.278,1.739,2.173,0.503,-0.156,0.859

In [40]:
from sklearn.cluster import KMeans
import sklearn.preprocessing as preprocessing
import sklearn.metrics as metrics
import pandas as pd
import numpy as np

df_train = pd.read_csv("data/data_train.csv")
df_test = pd.read_csv("data/data_test.csv")

df_stats = pd.DataFrame(df_train, columns=['account_1', 'account_2', 'account_3', 'account_4', 'account_5', 'account_6', 'account_7', 'account_8', 'account_9', 'account_10', 'account_11', 'account_12'])
mean=df_stats.mean()
std=df_stats.std()

cluster = df_train['cluster']
sd_train=((df_train-mean)/std).round(3)
# sd_train['cluster']=cluster

cluster = df_test['cluster']
sd_test=((df_test-mean)/std).round(3)
# sd_test['cluster']=cluster

In [41]:
sd_train

,account_1,account_10,account_11,account_12,account_2,account_3,account_4,account_5,account_6,account_7,account_8,account_9,cluster
0,1.238,0.860,-1.021,-1.300,-0.001,1.437,0.639,-0.097,-0.274,0.645,-1.155,-0.381,NaN
1,0.802,1.660,-0.036,1.497,1.290,-1.333,-1.211,-1.376,1.445,0.819,1.184,1.145,NaN
2,1.243,0.900,-1.043,-1.485,0.170,1.413,0.661,-0.147,-0.301,0.760,-1.265,-0.338,NaN
3,-0.202,-0.857,-0.036,-0.877,-0.851,0.089,-0.003,1.844,-1.281,-1.431,-0.851,-0.849,NaN
4,0.688,-0.348,1.043,0.301,0.520,0.334,0.121,0.002,0.689,-0.455,1.104,0.949,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,1.091,0.814,-0.968,-1.480,0.212,1.454,0.716,-0.171,-0.160,0.521,-1.086,-0.577,NaN
946,1.016,1.256,-0.193,1.264,1.270,-1.324,-1.076,-1.251,1.529,0.910,1.148,0.978,NaN
947,0.737,-0.393,0.915,0.078,0.554,0.250,0.232,-0.120,0.836,-0.522,1.128,0.853,NaN
948,0.707,1.280,-0.171,1.384,1.320,-1.445,-1.285,-1.398,1.390,0.960,1.036,1.027,NaN
949,0.625,1.348,0.023,1.577,1.549,-1.277,-1.261,-1.297,1.835,1.091,1.048,1.111,NaN